#!/usr/bin/env python3
"""
File System Watcher - Monitors a drop folder for new files.

This is the simplest watcher implementation, perfect for the Bronze tier.
It watches a designated "drop folder" and creates action files when new
files are added.

Usage:
    python filesystem_watcher.py /path/to/vault /path/to/drop_folder
"""

import sys
import time
import shutil
from pathlib import Path
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler, FileCreatedEvent

from base_watcher import BaseWatcher, load_processed_ids, save_processed_ids


class DropFolderHandler(FileSystemEventHandler):
    """Handles file system events for the drop folder."""
    
    def __init__(self, watcher):
        """
        Initialize the handler.
        
        Args:
            watcher: The FilesystemWatcher instance
        """
        self.watcher = watcher
        
    def on_created(self, event):
        """Called when a file or directory is created."""
        if event.is_directory:
            return
            
        source_path = Path(event.src_path)
        
        # Skip hidden files and temporary files
        if source_path.name.startswith('.') or source_path.suffix == '.tmp':
            return
            
        self.watcher.process_file(source_path)


class FilesystemWatcher(BaseWatcher):
    """
    Watches a drop folder for new files and creates action files.
    
    This is ideal for Bronze tier as it:
    - Requires no API credentials
    - Works completely offline
    - Demonstrates the watcher pattern clearly
    """
    
    def __init__(self, vault_path: str, drop_folder_path: str = None, check_interval: int = 5):
        """
        Initialize the filesystem watcher.
        
        Args:
            vault_path: Path to the Obsidian vault
            drop_folder_path: Path to the drop folder (defaults to vault/Inbox)
            check_interval: How often to check (in seconds)
        """
        super().__init__(vault_path, check_interval)
        
        self.drop_folder = Path(drop_folder_path) if drop_folder_path else self.inbox
        self.drop_folder.mkdir(parents=True, exist_ok=True)
        
        # Load processed file cache
        self.processed_ids = load_processed_ids(self.vault_path, 'filesystem')
        
        self.logger.info(f'Drop folder: {self.drop_folder}')
        
    def check_for_updates(self) -> list:
        """
        Check the drop folder for new files.
        
        Returns:
            List of new file paths to process
        """
        new_files = []
        
        for file_path in self.drop_folder.iterdir():
            if file_path.is_file() and not file_path.name.startswith('.'):
                file_id = str(file_path.absolute())
                if file_id not in self.processed_ids:
                    new_files.append(file_path)
                    
        return new_files
    
    def process_file(self, file_path: Path):
        """
        Process a newly dropped file.
        
        Args:
            file_path: Path to the file to process
        """
        try:
            action_file = self.create_action_file(file_path)
            self.logger.info(f'Created action file: {action_file.name}')
        except Exception as e:
            self.logger.error(f'Error processing file {file_path}: {e}')
    
    def create_action_file(self, file_path: Path) -> Path:
        """
        Create a markdown action file for the dropped file.
        
        Args:
            file_path: Path to the dropped file
            
        Returns:
            Path to the created action file
        """
        # Generate unique ID
        file_id = str(file_path.absolute())
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        # Create action file content
        content = f'''---
type: file_drop
source: filesystem
original_name: {file_path.name}
original_path: {file_path.absolute()}
size: {file_path.stat().st_size} bytes
received: {datetime.now().isoformat()}
status: pending
priority: normal
---

# File Drop for Processing

A new file was dropped for AI Employee processing.

## File Details

- **Original Name**: {file_path.name}
- **Size**: {file_path.stat().st_size} bytes
- **Received**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Source**: Drop Folder

## Suggested Actions

- [ ] Review file contents
- [ ] Determine required action
- [ ] Execute action or create plan
- [ ] Move to /Done when complete

## Notes

<!-- Add your notes here -->

---
*Generated by Filesystem Watcher v0.1*
'''
        
        # Create action file path
        action_filename = f'FILE_{timestamp}_{file_path.stem}.md'
        action_file_path = self.needs_action / action_filename
        
        # Write action file
        action_file_path.write_text(content)
        
        # Mark as processed
        self.processed_ids.add(file_id)
        save_processed_ids(self.vault_path, 'filesystem', self.processed_ids)
        
        return action_file_path
    
    def run_with_observer(self):
        """
        Run the watcher using watchdog observer (real-time file monitoring).
        
        This is more efficient than polling and provides instant response.
        """
        self.logger.info(f'Starting FilesystemWatcher with real-time monitoring')
        self.logger.info(f'Drop folder: {self.drop_folder}')
        
        event_handler = DropFolderHandler(self)
        observer = Observer()
        observer.schedule(event_handler, str(self.drop_folder), recursive=False)
        observer.start()
        
        self.logger.info(f'Watching for new files in {self.drop_folder}')
        
        try:
            while True:
                time.sleep(self.check_interval)
        except KeyboardInterrupt:
            self.logger.info('Stopping watcher...')
            observer.stop()
        except Exception as e:
            self.logger.error(f'Error: {e}')
            observer.stop()
            
        observer.join()
        self.logger.info('FilesystemWatcher stopped')


def main():
    """Main entry point for the filesystem watcher."""
    if len(sys.argv) < 2:
        print('Usage: python filesystem_watcher.py <vault_path> [drop_folder_path]')
        print('  vault_path: Path to the Obsidian vault')
        print('  drop_folder_path: Path to the drop folder (optional, defaults to vault/Inbox)')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    drop_folder_path = sys.argv[2] if len(sys.argv) > 2 else None
    
    # Validate vault path
    if not Path(vault_path).exists():
        print(f'Error: Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    watcher = FilesystemWatcher(vault_path, drop_folder_path)
    
    # Use real-time observer for better responsiveness
    watcher.run_with_observer()


if __name__ == '__main__':
    main()
